config/routes.rb
Rails.application.routes.draw do
	root 'posts#index'
	devise_for :users 
	resources :posts  
	resources :tags, only: [:show]
	resources :users	
	get '/subscribe', to: 'users#subscribe' 
	get '/unsubscribe', to: 'users#unsubscribe'
	get '/digest', to: 'posts#digest' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user

	has_many :taggings, dependent: :destroy	
	has_many :tags, through: :taggings, dependent: :destroy
		
	validates :title, :body, presence: true

	def all_tags
		self.tags.map(&:name).join(', ')			
	end

	def all_tags=(names)
		self.tags = names.split(',').map do |name|
		Tag.where(name: name.strip).first_or_create!
		end
	end

	mount_uploader :background, BackgroundUploader 
end

app/models/tag.rb
class Tag < ApplicationRecord

	has_many :taggings	
	has_many :posts, through: :taggings

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  validates :username, :email, presence: true
  
  mount_uploader :avatar, AvaUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types  :success, :danger, :info, :warning
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password,:username, :avatar) }
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation,:username, :avatar) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation,:username, :avatar) }
  end

     
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :set_post, only: [:show, :edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def show
	end

	def new
		@post = Post.new
	end

	def create  
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save
			redirect_to @post
		else
			render :new
		end
	end

	def edit 
	end

	def update
		if @post.update_attributes(post_params)
			redirect_to @post, success: 'Статья успешно обновлена' 
		else
			render :edit, danger: 'Статья не обновлена'
		end 
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	def digest 
		if params[:subscribe_status].blank? || ![1,2,3].include?(params[:subscribe_status].to_i)
  			response = { "error" => "нет такого статуса" }
  			render json: response, status: :bad_request
  			return
		end
		@subscribe_status = params[:subscribe_status]
		@users = User.where(is_admin: false, subscribe: true, subscribe_status: @subscribe_status)
		@posts = Post.includes(:user).where(users: {is_admin: true})
		
		if @subscribe_status = 1
			@date = Time.now - 1.days
			@posts = @posts.where(created_at: @date.beginning_of_day..@date.end_of_day) 
		elsif @subscribe_status = 2  
			@date = Time.now - 1.week
			@posts = @posts.where(created_at: @date.beginning_of_day..@date.end_of_day) 
		else
			@date = Time.now - 1.month
			@posts = @posts.where(created_at: @date.beginning_of_day..@date.end_of_day) 
		end

		@users.each do |user|
			ap user
			PostMailer.new_post_email(user, @posts).deliver_now 	
		end	

		return render json: true	
	end

private
	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :summary, :body, :background, :all_tags) 
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	
	
	def show
		@tag = Tag.find_by(name: params[:id])
		@posts = @tag.posts
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:index, :edit, :update, :destroy]

	def index
	end

	def edit
	end

	def update
		if @user.update_attributes(user_params)
			redirect_to root_path, success: 'Данные пользователя обновлены' 
		else
			render :edit, danger: 'Новые данные не сохранены'
		end 
	end

	def subscribe
		@user = current_user
		@user.update_attribute(:subscribe, true)
		@user.save
		redirect_to root_path
	end

	def unsubscribe
		@user = current_user
		@user.update_attribute(:subscribe, false)
		@user.save
		redirect_to root_path
	end


	private
		def set_user
			@user = current_user
		end

		def user_params
			params.require(:user).permit(:username, :email, :avatar, :subscribe_status) 
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"]
    meta[name="description" content=""]
    meta[name="author" content=""]
    title
      | Clean Blog - Start Bootstrap Theme
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'clean-blog.min', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'clean-blog.min', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://cdn.embedly.com/widgets/platform.js', 'data-turbolinks-track': 'reload', 'charset': 'UTF-8'
    link[href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css"]
    link[href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css"]
  body
    = yield

app/views/posts/_errors.html.slim
- if @post.errors.any?
  .alert.alert-danger
    h5= t('common.errors')
    ul
      - @post.errors.full_messages.each do  |message|
        li= message

app/views/posts/_form.html.slim
= render 'errors'
= form_for @post, html:{ multipart: true } do |f|
  .form-group.row
    = f.label :title, :class => 'col-sm-2 col-form-label'
    .col-sm-10
      = f.text_field :title, :class => 'form-control', :placeholder => t('posts.title')
  .form-group.row
    = f.label :summary, :class => 'col-sm-2 col-form-label'
    .col-sm-10
      = f.text_area :summary, :class => 'form-control', :placeholder => t('posts.summary')
  .form-group.row
    = f.label :all_tags, :class => 'col-sm-2 col-form-label'
    .col-sm-10
      = f.text_field :all_tags, :class => 'form-control', :id => 'tags', :placeholder => t('posts.all_tags'), data: {autocomplete_source: Tag.order(:name).map(&:name)}   
    javascript:
      $('#tags'). autocomplete({
        source:  $('#tags').data('autocomplete-source')
      });  
  .form-group.row
    = f.label :body, :class => 'col-sm-2 col-form-label'
    .col-sm-10
      = f.text_area :body, :class => 'form-control', :id => 'text_edit_field', :placeholder => :body
    javascript:
       $('#text_edit_field').froalaEditor({toolbarInline: false, language: 'ru'});
  .form-group.row
    = f.label :background, :class => 'col-sm-2 col-form-label'
    .col-sm-10
      = f.file_field :background, :class => 'form-control'
  .form-group.row
    .col-sm-10
      = f.submit t('.submit'), :class => 'btn btn-primary'

app/views/posts/_header.html.slim
body
  header.masthead style=("background-image: url('#{asset_path('home-bg.jpg')}')") 
    .overlay
    .container
      .row
        .col-lg-8.col-md-10.mx-auto
          .site-heading
            h1= t('header.heading')
            span.subheading= t('header.sub')
            br/
            = t('header.welcome', username: current_user.username)
            - flash.each do |name, message|
              div class=("alert alert-#{name}") 
                = message

app/views/posts/_header_min.html.slim
body
  header.masthead style=("max-height: 75px; margin-bottom:150px; background-image: url('#{asset_path('home-bg.jpg')}')") 
    .overlay
    .container
      .row
        .col-lg-8.col-md-10.mx-auto
          .site-heading
            

app/views/posts/_nav.html.slim
= stylesheet_link_tag    'top-profile', media: 'all', 'data-turbolinks-track': 'reload'
nav#mainNav.navbar.navbar-expand-lg.navbar-light.fixed-top
  .container
    = link_to t('nav.home'), posts_path, :class => 'navbar-brand'
    button.navbar-toggler.navbar-toggler-right aria-controls="navbarResponsive" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarResponsive" data-toggle="collapse" type="button" 
      = t('nav.menu')
    #navbarResponsive.collapse.navbar-collapse
      ul.navbar-nav.ml-auto
        li.nav-item
          = link_to t('nav.new'), new_post_path
        li.dropdown.nav-item
          a.dropdown-toggle.nav-link aria-expanded="false" data-toggle="dropdown" href="#" role="button" 
            = current_user.username
          ul.dropdown-menu role="menu" style=("left: -125px") 
            li.dropdown-item
              .container
                .row
                  .col-lg-12.col-sm-6
                    .card.hovercard
                      .cardheader
                      .avatar
                        img alt="#{current_user.avatar}" src="#{current_user.avatar.url(:thumb)}" /
                      .info
                        .title
                          = link_to current_user.username, users_path
                        .desc
                          | E-mail: #{current_user.email}
              .text-center
                = link_to t('nav.exit'), destroy_user_session_path, :class => 'btn btn-danger', :style => ' padding: 3px 25px; border-radius: 15px;', :method => :delete, data: {confirm: t('nav.confirm')}

app/views/posts/_post.html.slim
.media
  img.align-self-center.mr-3 alt="#{post.background}" src="#{post.background.url(:thumb)}" /
  .media-body
    h2.mt-0= link_to post.title, post_path(post)
    p.post-meta.mt-0
      = t('post.by')
      = post.user.username
    time.text-muted
      = Russian::strftime(post.created_at.to_date, '%d %B %Y')
= t('post.tags')
section.footer-summary
  == post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'badge badge-primary' }.join(' ')
hr/

app/views/posts/edit.html.slim
= render 'nav'
= render 'header_min'
.container
  h1
    = t('posts.edit.title')
  br/
  .row
    .col-md-6
      - flash.each do |name, message|
        div class=("alert alert-#{name}") 
          = message
  = render 'form'

app/views/posts/index.html.slim
= render 'nav'
= render 'header'
.container
  .row
    .col-lg-8.col-md-10.mx-auto
      .post-preview
        = render @posts
/! Footer
footer
  .container
    .row
      .col-lg-8.col-md-10.mx-auto
        p.copyright.text-muted Copyright © Easy blog 2018

app/views/posts/new.html.slim
= render 'nav'
= render 'header_min'
.container
  h1= t('posts.new.title')
  br/
  = render 'form'

app/views/posts/show.html.slim
body
  = render 'nav'
  header.masthead style=("background-image: url('#{@post.background.url(:large)}')") 
    .overlay
    .container
      .row
        .col-lg-8.col-md-10.mx-auto
          .post-heading
            h1= @post.title
            h2.subheading= @post.summary
            - if current_user.id == @post.user.id
              = link_to t('common.edit'), edit_post_path(@post), :class => 'btn btn-outline-warning'
              |&nbsp;
              = link_to t('common.delete'), post_path(@post), method: :delete, data: {confirm: 'Вы уверены?'}, :class => 'btn btn-outline-danger'
            - if !current_user.is_admin
              - if !current_user.subscribe
                = link_to t('subscribe.sub', adminname: User.find(1).username), subscribe_path,  :class => 'btn btn-outline-info'
              - else
                = link_to t('subscribe.unsub', adminname: User.find(1).username), unsubscribe_path,  :class => 'btn btn-outline-warning'
  /! Post Content
  article
    .container
      .row
        .col-lg-8.col-md-10.mx-auto
          .row
            .col-md-6
              - flash.each do |name, message|
                div class=("alert alert-#{name}") 
                  = message
          == @post.body
          | Tags:
          .footer-summary
            == @post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'badge badge-primary' }.join(' ')
          br/
          span.meta
            = t('post.by')    
            = @post.user.username
            br/
            time.text-muted
              = Russian::strftime(@post.created_at.to_date, '%d %B %Y')

app/views/tags/show.html.slim
= render 'posts/nav'
= render 'posts/header'
.container
  h1
    | Filtred by tag: ##{@tag.name}
  - if @tag.posts.empty?
    h2 No posts
  - else
    .container
      .row
        .col-lg-8.col-md-10.mx-auto
          .post-preview
            a href="post.html" 
              = render @tag.posts
          /! Pager
          .clearfix
            a.btn.btn-primary.float-right href="#"  Older Posts →
    hr/

app/views/users/_errors.html.slim
- if @user.errors.any?
  .alert.alert-danger
    h5= t('common.errors')
    ul
      - @user.errors.full_messages.each do  |message|
        li= message

app/views/users/index.html.slim
= stylesheet_link_tag  'profile', media: 'all', 'data-turbolinks-track': 'reload'
= render 'posts/nav'
= render 'posts/header'
.container.emp-profile
  = render 'errors'
  = form_for @user, html:{ multipart: true } do |f|
    .row
      - if current_user.avatar != ''
        .col-md-4
          .profile-img
            img alt="#{current_user.avatar}" src="#{current_user.avatar.url(:large)}" /
            .file.btn.btn-lg.btn-primary
              = t('users.index.photo')
              = f.file_field :avatar
      - else
        .col-md-8
          .col-md-12
            .profile-head
              h5
                = current_user.username
    .row style=("margin-top: -250px")
      .col-md-4
      .col-md-8
        .form-group.row
          = f.label :email, :class => 'col-md-6 col-form-label form-control-label'
          .col-md-6
            = f.email_field :email, autofocus: true, autocomplete: "email", :class => 'form-control'
        .form-group.row
          = f.label :username, :class => 'col-md-6 col-form-label form-control-label'
          .col-md-6
            = f.text_field :username, autofocus: true, autocomplete: "username", :class => 'form-control'
        - if current_user.is_admin = false     
          .form-group.row
            = f.label :subscribe_status, :class => 'col-md-6 col-form-label form-control-label'
            .col-md-6
              = f.select :subscribe_status, options_for_select([[t('subscribe.daily'), 1], [t('subscribe.weekly'), 2], [t('subscribe.mouthly'),3]], current_user.subscribe_status), :class => 'form-control'
        .col-lg-10
          = f.submit t('users.index.submit'), :class => 'btn btn-primary' 
          |&nbsp;
          = link_to t('common.back'), :back, :class => 'btn  btn-info'